### ISSUE TITLE
create workflow figure

### ISSUE THREAD

**Issue by k8hertweck** [fredhutchio/rnaseq#14]
We need to create a figure resembling [this one](https://www.ebi.ac.uk/training/online/courses/functional-genomics-ii-common-technologies-and-data-analysis-methods/rna-sequencing/performing-a-rna-seq-experiment/) that includes the main points we'll be covering in this course. I've sketched out what this would look like:

![IMG_4008](https://user-images.githubusercontent.com/1678233/114913459-107b2480-9dd6-11eb-9705-73be4ebe89ba.jpg)

We need to recreate this figure, preferably using [draw.io](https://app.diagrams.net). We should save both the png and editable draw.io file.

**Comment by k8hertweck** [comment]
We should also document how we end up creating images in the instructor contribution repo, but we can table that for now.

**Comment by lakikowolfe** [comment]
@k8hertweck check out the draft I committed to the gh-pages branch! It's in `concepts/imgs`

**Comment by k8hertweck** [comment]
This is great, thanks!
